#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  lEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rEnc,           sensorQuadEncoder)
#pragma config(Motor,  port1,           lbDrive,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port8,           lfDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rfDrive,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rbDrive,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "advanced.c"
task pre_auton
{
}
task autonomous()
{

}
task main()
{
	while(1==1)
	{
		motor[lbDrive]=vexRT[Ch3];
		motor[lfDrive]=vexRT[Ch3];
		motor[rbDrive]=vexRT[Ch2];
		motor[rfDrive]=vexRT[Ch2];

	}

}
